name: Run Script

on:
  push:
  workflow_dispatch:  # Added manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v3  # Updated to the latest version
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt

    - name: Run script
      run: |
        python python/scrape-tubi.py
        
    - name: Verify generated files
      run: |
        ls -la python/tubi_epg_us.xml
        ls -la python/tubi_playlist_us.m3u
